name: flutter_getx_cli
description: A command-line tool for GetX to automate module creation.
version: 1.0.6
homepage: https://github.com/DilshadAlam98/flutter_getx_cli.git
repository: https://github.com/DilshadAlam98/flutter_getx_cli.git

environment:
  sdk: ^3.9.2

dependencies:
  dio: ^5.9.0
  get: ^4.7.3
  get_it: ^9.2.0
  shared_preferences: ^2.5.4

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

executables:
  flutter_getx_cli: getx_cli
